spring:
  application:
    name: Mystery Project
  frontend-client: http://localhost:5173
  config:
    import: "env.properties"
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/mystery
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    name: ${DB_NAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  logging:
    level:
      org:
        hibernate:
          SQL: false
  token:
    signing:
      key: ${TOKEN_KEY}
  security:
    user:
      name: ${SECURITY_USER}
      password: ${SECURITY_PASSWORD}
