spring:
  application:
    name: Mystery Project
  frontend-client: http://localhost:5173
  config:
    import: "env.properties"
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/mystery
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    name: ${DB_NAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
  logging:
    level:
      org:
        hibernate:
          SQL: false
  mail:
    host: ${MAIL_TRAP}
    port: ${MAIL_TRAP_PORT}
    username: ${MAIL_TRAP_USERNAME}
    password: ${MAIL_TRAP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 3000
      mail.smtp.writetimeout: 5000

