spring:
  application:
    name: Mystery Project
  config:
    import:
      "env.properties"
  frontend-client: http://localhost:5173
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/mystery
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    logging:
      level:
        org:
          hibernate:
            SQL: false
          springframework:
            security: TRACE
    token:
      signing:
        key: ${TOKEN_KEY}
  security:
    user:
      name: ${SECURITY_USER}
      password: ${SECURITY_PASSWORD}
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_CLIENT_ID}
            client-secret: ${OAUTH_CLIENT_SECRET}
            scope: profile,email
            redirect-uri: "${BASE_URL}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            user-name-attribute: sub


