package com.mystery.project.entities.email;

public class CreateEmailHtmlPages {

  public static String generatePasswordResetEmail(String resetLink) {
    return "<!DOCTYPE html>"
        + "<html lang=\"en\">"
        + "<head>"
        + "    <meta charset=\"UTF-8\">"
        + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
        + "    <title>Password Reset</title>"
        + "    <style>"
        + "        body {"
        + "            font-family: Arial, sans-serif, 'Helvetica', 'sans-serif';"
        + "            background-color: #f4f4f9;"
        + "            margin: 0;"
        + "            padding: 0;"
        + "            color: #333;"
        + "        }"
        + "        .email-container {"
        + "            width: 100%;"
        + "            max-width: 600px;"
        + "            margin: 0 auto;"
        + "            background-color: #fff;"
        + "            border-radius: 8px;"
        + "            padding: 20px;"
        + "            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);"
        + "        }"
        + "        h2 {"
        + "            text-align: center;"
        + "            color: #4CAF50;"
        + "            margin: 0;"
        + "        }"
        + "        p {"
        + "            font-size: 16px;"
        + "            line-height: 1.5;"
        + "            text-align: center;"
        + "        }"
        + "        .reset-link {"
        + "            display: inline-block;"
        + "            background-color: #4CAF50;"
        + "            color: #fff;"
        + "            padding: 12px 24px;"
        + "            text-decoration: none;"
        + "            font-size: 16px;"
        + "            border-radius: 5px;"
        + "            margin-top: 20px;"
        + "        }"
        + "        .reset-link:hover {"
        + "            background-color: #45a049;"
        + "        }"
        + "        .footer {"
        + "            text-align: center;"
        + "            margin-top: 30px;"
        + "            font-size: 14px;"
        + "            color: #888;"
        + "        }"
        + "    </style>"
        + "</head>"
        + "<body>"
        + "    <table class=\"email-container\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">"
        + "        <tr>"
        + "            <td>"
        + "                <h2>Password Reset Request</h2>"
        + "                <p>We received a request to reset your password. If you did not request this, please ignore this email.</p>"
        + "                <p>Click the button below to reset your password:</p>"
        + "                <a href=\""
        + resetLink
        + "\" class=\"reset-link\">Reset Password</a>"
        + "                <div class=\"footer\">"
        + "                    <p>If you're having trouble, contact us at support@mysteryproject.com</p>"
        + "                </div>"
        + "            </td>"
        + "        </tr>"
        + "    </table>"
        + "</body>"
        + "</html>";
  }
}
